COLUMNS:
    Time: float64
    V1: float64
    V2: float64
    V3: float64
    V4: float64
    V5: float64
    V6: float64
    V7: float64
    V8: float64
    V9: float64
    V10: float64
    V11: float64
    V12: float64
    V13: float64
    V14: float64
    V15: float64
    V16: float64
    V17: float64
    V18: float64
    V19: float64
    V20: float64
    V21: float64
    V22: float64
    V23: float64
    V24: float64
    V25: float64
    V26: float64
    V27: float64
    V28: float64
    Amount: float64


TARGET_COLUMN:
  name: quality
  